### PR TITLE
Reimplement recursive code to use trampolines to prevent stack overflows

### LINKED ISSUE #162: Prevent stack overflows during parsing caused by recursive implementation by using trampolines
Because Metal is implemented with as little mutable state as possible, many functionality is implemented using recursion. Since the JVM does not currently implement tail call elimination, this regularly leads to stack overflows.

The goal is to prevent these stack overflows by letting the recursive functions use trampolines. This is a mechanism that encodes the next recursive step into a method (typically using a lambda expression) that can be popped off the stack and executed. As a result, this allows a recursive style of programming without the stack overflow issue.

Recursion is used extensively in Metal. The first step (and goal of this issue) is to reimplement all recursive code using trampolines that can get executed during parsing. So this includes:

`Token`s:
 - [x] `Rep`
 - [x] `RepN`
 - [x] `Seq`
 - [x] `Cho`
 - [x] `While`
 - [x] `Sub`, which delegates to `ByOffset.hasRootAtOffset()`
 - [x] `Tie`
 - [x] `TokenRef` (tree processing, see below)

`ValueExpression`s:
 - [x] `NameRef`, which delegates to `ByName.getAllValues()` and `Wrapping.wrap()`
 - [x] `TokenRef`, which delegates to `ByToken.getAllValues()` and `Wrapping.wrap()`
 - [x] `First`
 - [x] `Nth`, which uses Reversal.reverse()
 - [x] `Reverse`, which delegates to `Reversal.reverse()`
 - [x] `Fold`
 - [x] `Expand`, which delegates to `ImmutableList.add(ImmutableList)`
 - [x] `BinaryValueExpression`
 - [x] `UnaryValueExpression`
 - [x] `Expand`
 - [x] `Elvis`

`Expression`s:
 - [x] `ComparisonExpression`

Data structures:
 - [x] `ImmutableList<T>` (`createFromArray()` method and `add(ImmutableList)` method, latter does tree processing, see below)
 - [x] `DataExpressionSource` (`getValueAtIndex()` method)
 - [x] `Callbacks` (`handleCallbacks()` method, note: it's `void`)

The remaining recursive code should also use trampolines (or be moved). This is addressed in #166.

Also to consider is recursion in four methods that are used a lot and a not prone to recursing extensively:  `ParseGraph`'s `add(ParseValue)`, `add(ParseReference)`, `addBranch()` and `closeBranch()`. This is discussed in #173.

One issue to consider is whether the `Trampoline.next()` method should throw an `IOException`. This is required by all `Token` implementations (except `TokenRef`) because `Token.parse()` throws it. It is unnecessary for the others. Possible solutions appear to be either wrapping the `IOException` (ugly) or creating two trampoline interfaces (duplication). Currently the latter is used: there are now `Trampoline` and `SafeTrampoline`, where the former's `next()` and `computeResult()` methods may throw an `IOException`.

Some methods are difficult to implement using only tail call recursion because they process a tree and handle both head and tail cases recursively, of which then only one is in the tail call. Converting these to trampolines as is can still result in stack overflows in some cases, so they need to be rewritten to tail call recursion. Below is a list of these cases as encountered during conversion:

 - [x] `ByOffset.getLowestOffsetValue()`
 - [x] `ByName.getAllValues()`
 - [x] `ByToken.getAllValues()`
 - [x] `ImmutableList.add(ImmutableList)`
 - [x] `TokenRef.lookup()`
 - [x] `ParseGraph.current()`
 - [x] `ByToken.getAllRoots()`

### PR DESCRIPTION
**Pull request by jvdb**
See #162 for details on all considerations and affected code. Additionally, note that some code is not reimplemented. Not converted code should either be discussed in #166 or #173.

Some conversions may seem complex, but this is because trampolines work with tail recursion, while some recursive code in Metal was not tail recursive. So this code had to be rewritten to both be tail recursive _and_ utilize trampolines. For examples, see the list at the bottom of #162.

There is quite a lot of use of the `Reversal.reverse(ImmutableList)` method in the new implementations. While this may seem to be slow, the alternative (where every step of the recursion changes the order) is actually much slower. So my suggestion is that we accept the final reverse step at the end of many of these computations.

Additionally, note that there are two trampoline implementations: `Trampoline` and `SafeTrampoline`. They duplicate almost all of their code. The only difference is that on `Trampoline`, the `next()` and `computeResult()` methods may throw can `IOException` as required by `Token.parse()`. My proposal here is to keep both implementations as there may be some changes into whether we keep the `IOException`, so doing some complex engineering around this may be unnecessary for now.

Also, some methods may look very similar due to the overlap in scaffolding in the trampolines. Note that there is also a separate issue to address this: #172. In order to keep the size of this already far too large PR down, I propose we keep the duplication for now.

Resolves #162.

### CODE REVIEW

File: core/src/main/java/io/parsingdata/metal/token/Cho.java [hunk 1]
```diff
@@ -43,27 +46,23 @@
...
-    private Optional<Environment> iterate(final String scope, final Environment environment, final Encoding encoding, final ImmutableList<Token> list) throws IOException {
+    private Trampoline<Optional<Environment>> iterate(final String scope, final Optional<Environment> environment, final Encoding encoding, final ImmutableList<Token> list) throws IOException {
         if (list.isEmpty()) {
-            return failure();
+            return complete(Util::failure);
         }
-        final Optional<Environment> result = list.head.parse(scope, environment, encoding);
-        if (result.isPresent()) { return result; }
-        return iterate(scope, environment, encoding, list.tail);
+        return list.head.parse(scope, environment.get(), encoding)
```
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/token/Cho.java]: Is this `environment.get()` safe?

File: core/src/main/java/io/parsingdata/metal/token/TokenRef.java [hunk 2]
```diff
@@ -60,22 +64,20 @@ public TokenRef(final String name, final String referenceName, final Encoding en
...
-        }
-        if (!item.isGraph() || item.asGraph().isEmpty()) { return LOOKUP_FAILED; }
-        final Token headResult = lookup(item.asGraph().head, referenceName);
-        if (headResult != LOOKUP_FAILED) { return headResult; }
-        return lookup(item.asGraph().tail, referenceName);
+    private SafeTrampoline<Token> lookup(final ImmutableList<ParseItem> items, final String referenceName) {
+        if (items.isEmpty()) { return complete(() -> LOOKUP_FAILED); }
+        final ParseItem item = items.head;
+        if (item.getDefinition().name.equals(referenceName)) { return complete(item::getDefinition); }
+        if (item.isGraph() && !item.asGraph().isEmpty()) { return intermediate(() -> lookup(items.tail.add(item.asGraph().tail).add(item.asGraph().head), referenceName)); }
```
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/token/TokenRef.java]: Move `if` bodies to new lines.

File: core/src/test/java/io/parsingdata/metal/TrampolineTest.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+    public void nextOnFinalSafeTrampoline() {
+        thrown.expect(UnsupportedOperationException.class);
+        thrown.expectMessage("A CompletedTrampoline does not have a next computation.");
+        ((SafeTrampoline.CompletedTrampoline<Integer>) () -> 42).next();
+    }
+
+    @Test
+    public void noStackOverflow() {
+        // The 100000th Fibonacci number has 20899 digits
+        Assert.assertEquals(20899, fibonacci(BigInteger.ZERO, BigInteger.ONE, 100000).computeResult().toString().length());
```
Comment (rdvdijk) [inline core/src/test/java/io/parsingdata/metal/TrampolineTest.java]: Neat :+1:

Nitpick: `static import` `assertEquals`.

File: core/src/main/java/io/parsingdata/metal/token/Pre.java [hunk 4]
```diff
@@ -57,7 +58,7 @@ public Pre(final String name, final Token token, final Expression predicate, fin
             return failure();
         }
         final Optional<Environment> result = token.parse(scope, environment.addBranch(this), encoding);
-        return result.isPresent() ? success(result.get().closeBranch()) : failure();
+        return result.map(resultEnvironment -> success(resultEnvironment.closeBranch())).orElseGet(Util::failure);
```
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/token/Pre.java]: Code style: In `Rep` (below), these span multiple lines, let's do that everywhere. So:

```java
return result
    .map(resultEnvironment -> success(resultEnvironment.closeBranch()))
    .orElseGet(Util::failure);
```

File: core/src/main/java/io/parsingdata/metal/SafeTrampoline.java [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.parsingdata.metal;
+
+public interface SafeTrampoline<T> {
```
Comment (ccreeten) [inline core/src/main/java/io/parsingdata/metal/SafeTrampoline.java]: But you will have to watch out not to use Foo as static type where Bar is used, as then users will have to handle IOException anyway.

File: core/src/test/java/io/parsingdata/metal/TrampolineTest.java (hunk 3 above)
Comment (ccreeten) [inline core/src/test/java/io/parsingdata/metal/TrampolineTest.java]: I wonder what the average stack size has to be in order for a standard recursive method to complete without overflow :smile:

File: core/src/main/java/io/parsingdata/metal/data/DataExpressionSource.java [hunk 6]
```diff
@@ -45,17 +48,17 @@ public DataExpressionSource(final ValueExpression dataExpression, final int inde
     protected byte[] getData(final long offset, final int size) throws IOException {
         final ImmutableList<Optional<Value>> results = dataExpression.eval(graph, encoding);
         if (results.size <= index) { throw new IllegalStateException("ValueExpression dataExpression yields " + results.size + " result(s) (expected at least " + (index + 1) + ")."); }
-        final byte[] inputData = getValueAtIndex(results, index, 0).get().getValue();
+        final byte[] inputData = getValueAtIndex(results, index, 0).computeResult().get().getValue();
```
Comment (ccreeten) [inline core/src/main/java/io/parsingdata/metal/data/DataExpressionSource.java]: This is a personal thing, but I prefer to create a method with ''logical/expected" parameters, which then passes extra necessary parameters to the computing method, e.g. in this case, you only call ```getValueAtIndex(results, index)```, even for private methods. (also, this method assumes that the given index is valid with respect to the list size?)

**Comment by ccreeten** [comment]
I know performance is not a thing as for now, but have you tested it on some real world cases to see what kind effect these refactorings have? Probably isn't too bad, but I think it is interesting to know.

File: core/src/main/java/io/parsingdata/metal/SafeTrampoline.java (hunk 5 above)
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/SafeTrampoline.java]: @ccreeten Good point. But I think we can take this risk as trampolines are never exposed in the public API, so it's purely an internal thing for us to deal with...

File: core/src/main/java/io/parsingdata/metal/Trampoline.java [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package io.parsingdata.metal;
+
+import java.io.IOException;
+
+public interface Trampoline<T> {
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/Trampoline.java]: I will add some documentation. JavaDoc is not necessary I think since we do not expose any trampolines in the public API. So it's only relevant for those maintaining/extending Metal.

File: core/src/main/java/io/parsingdata/metal/data/ImmutableList.java [hunk 8]
```diff
@@ -59,9 +63,13 @@ private ImmutableList(final T head, final ImmutableList<T> tail) {
 
     public ImmutableList<T> add(final ImmutableList<T> list) {
         checkNotNull(list, "list");
-        if (list.isEmpty()) { return this; }
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/ImmutableList.java]: It's a duplicate check, especially since it cannot be removed from the `addRecursive()` method (as that is peeling off the `list` and needs the empty check to end recursion eventually). So if we keep it there we have duplicate code as well as a redundant duplicate check on all added non-empty lists.

File: core/src/main/java/io/parsingdata/metal/data/ParseGraph.java [hunk 9]
```diff
@@ -97,15 +100,15 @@ ParseGraph closeBranch() {
...
     public ParseValue current() {
-        if (isEmpty()) { return null; }
-        if (head.isValue()) {
-            return head.asValue();
-        }
-        if (head.isGraph()) {
-            final ParseValue value = head.asGraph().current();
-            if (value != null) { return value; }
-        }
-        return tail.current(); // Ignore current if it's a reference (or an empty graph)
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/ParseGraph.java]: I removed it on purpose because it doesn't add much to the understanding of the code but could turn stale if we ever add another type of `ParseItem`.

File: core/src/main/java/io/parsingdata/metal/data/ParseGraph.java [hunk 10]
```diff
@@ -97,15 +100,15 @@ ParseGraph closeBranch() {
...
+        return current(ImmutableList.create(this)).computeResult();
+    }
+
+    private SafeTrampoline<ParseValue> current(ImmutableList<ParseItem> items) {
+        if (items.isEmpty()) { return complete(() -> null); }
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/ParseGraph.java]: See #161. There are some situations (especially with `ValueExpression`s, where the default return value is already an `Optional`) where it won't be straightforward to remove the use of `null`. But I think this one can actually quite easily be fixed :)

File: core/src/main/java/io/parsingdata/metal/data/ParseGraph.java [hunk 11]
```diff
@@ -97,15 +100,15 @@ ParseGraph closeBranch() {
...
+        final ParseItem item = items.head;
+        if (item.isValue()) { return complete(item::asValue); }
+        if (item.isGraph() && !item.asGraph().isEmpty()) { return intermediate(() -> current(items.tail.add(item.asGraph().tail).add(item.asGraph().head))); }
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/ParseGraph.java]: Turned it into _four_ lines...

File: core/src/main/java/io/parsingdata/metal/data/selection/ByName.java [hunk 12]
```diff
@@ -56,20 +60,21 @@ public static ParseValue getValue(final ParseGraph graph, final String name) {
     public static ImmutableList<Value> getAllValues(final ParseGraph graph, final String name) {
         checkNotNull(graph, "graph");
         checkNotNull(name, "name");
-        return getAllValuesRecursive(graph, name);
+        return reverse(getAllValuesRecursive(ImmutableList.create(graph), new ImmutableList<>(), name).computeResult());
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/selection/ByName.java]: Everywhere where a `reverse()` was added where it didn't occur originally is because of the way the data structure is constructed: in the non-tail recursive implementations, the following pattern is used when traversing the data structure:

Are we currently at a match?
* No -> Return recurse.
* Yes -> X = Recurse. Add current result to X. Return X.

This ensures that the constructed data structure mirrors that of the original in that the _deepest_ match is put in the deepest part of the returned structure.

When converting to tail recursion, we cannot add something to the result of a recursive call, because we _must_ end with the recursive call. So instead we pass along an intermediate result that we add our local result to. But that means that the _first_ match ends up in the _deepest_ part of the resulting data structure.

So we end up calling `reverse()` on the final result to mirror the original order.

File: core/src/main/java/io/parsingdata/metal/data/ImmutableList.java (hunk 8 above)
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/data/ImmutableList.java]: Yes, I saw that it was added in the recursive step. The one reason for my comment is that if we leave the check here, there is no need for a trampoline at all. A _very_ minor optimization.

File: core/src/main/java/io/parsingdata/metal/data/selection/ByName.java [hunk 13]
```diff
@@ -56,20 +60,21 @@ public static ParseValue getValue(final ParseGraph graph, final String name) {
...
         if (head.isValue() && head.asValue().matches(name)) {
-            return tailResults.add(head.asValue());
+            return intermediate(() -> getAllValuesRecursive(graphList.tail.add(graph.tail), values.add(head.asValue()), name));
         }
         if (head.isGraph()) {
-            return tailResults.add(getAllValuesRecursive(head.asGraph(), name));
+            return intermediate(() -> getAllValuesRecursive(graphList.tail.add(graph.tail).add(graph.head.asGraph()), values, name));
         }
-        return tailResults;
+        return intermediate(() -> getAllValuesRecursive(graphList.tail.add(graph.tail), values, name));
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/selection/ByName.java]: Wow indeed! Implemented! I named the methods `addIfGraph()` and `addIfMatchingValue()` to express what they do.

File: core/src/main/java/io/parsingdata/metal/data/selection/ByOffset.java [hunk 14]
```diff
@@ -31,35 +34,39 @@
...
         if (graph.head.isValue()) {
-            return getLowestOffsetValue(graph.tail, lowest == null || lowest.slice.offset > graph.head.asValue().slice.offset ? graph.head.asValue() : lowest);
+            return intermediate(() -> getLowestOffsetValue(graphList.tail.add(graph.tail), lowest == null || lowest.slice.offset > graph.head.asValue().slice.offset ? graph.head.asValue() : lowest));
         }
         if (graph.head.isGraph()) {
-            return getLowestOffsetValue(graph.tail, getLowestOffsetValue(graph.head.asGraph(), lowest));
+            return intermediate(() -> getLowestOffsetValue(graphList.tail.add(graph.head.asGraph()).add(graph.tail), lowest));
         }
-        return getLowestOffsetValue(graph.tail, lowest);
+        return intermediate(() -> getLowestOffsetValue(graphList.tail.add(graph.tail), lowest));
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/selection/ByOffset.java]: Agreed. I think instead of refactoring many methods to a similar pattern, we should postpone that and do it as part of #172.

File: core/src/main/java/io/parsingdata/metal/data/selection/ByToken.java [hunk 15]
```diff
@@ -68,38 +72,46 @@ public static ParseItem get(final ParseGraph graph, final Token definition) {
...
-        checkNotNull(definition, "definition");
-        return getAllRootsRecursive(graph, null, definition);
+        return getAllRootsRecursive(ImmutableList.create(new Pair(checkNotNull(graph, "graph"), null)), checkNotNull(definition, "definition"), new ImmutableList<>()).computeResult();
     }
 
-    private static ImmutableList<ParseItem> getAllRootsRecursive(final ParseItem item, final ParseGraph parent, final Token definition) {
-        final ImmutableList<ParseItem> result = item.getDefinition().equals(definition) && (parent == null || !parent.getDefinition().equals(definition))
-            ? ImmutableList.create(item)
-            : new ImmutableList<>();
+    private static SafeTrampoline<ImmutableList<ParseItem>> getAllRootsRecursive(final ImmutableList<Pair> list, final Token definition, final ImmutableList<ParseItem> result) {
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/selection/ByToken.java]: Renamed `list` to `backlog` (because it's the list of roots that still need to be checked) and `result` to `rootList` (because it's the list of found roots).

File: core/src/main/java/io/parsingdata/metal/data/selection/ByToken.java [hunk 16]
```diff
@@ -68,38 +72,46 @@ public static ParseItem get(final ParseGraph graph, final Token definition) {
...
         if (item.isGraph() && !item.asGraph().isEmpty()) {
-            return result
-                .add(getAllRootsRecursive(item.asGraph().tail, item.asGraph(), definition))
-                .add(getAllRootsRecursive(item.asGraph().head, item.asGraph(), definition));
+            return intermediate(() -> getAllRootsRecursive(list.tail.add(new Pair(item.asGraph().head, item.asGraph())).add(new Pair(item.asGraph().tail, item.asGraph())), definition, nextResult));
+        }
+        return intermediate(() -> getAllRootsRecursive(list.tail, definition, nextResult));
+    }
+
+    static class Pair {
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/selection/ByToken.java]: Makes sense, but I don't want to clutter it too much with helper method definitions.

File: core/src/main/java/io/parsingdata/metal/expression/value/Fold.java [hunk 17]
```diff
@@ -58,23 +61,24 @@ public Fold(final ValueExpression values, final BinaryOperator<ValueExpression>
...
         if (initial.size > 1) { return new ImmutableList<>(); }
         final ImmutableList<Optional<Value>> values = prepareValues(this.values.eval(graph, encoding));
-        if (values.isEmpty() || containsEmpty(values)) { return initial; }
+        if (values.isEmpty() || containsEmpty(values).computeResult()) { return initial; }
         if (!initial.isEmpty()) {
-            return ImmutableList.create(fold(graph, encoding, reducer, initial.head, values));
+            return ImmutableList.create(fold(graph, encoding, reducer, initial.head, values).computeResult());
         }
-        return ImmutableList.create(fold(graph, encoding, reducer, values.head, values.tail));
+        return ImmutableList.create(fold(graph, encoding, reducer, values.head, values.tail).computeResult());
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/expression/value/Fold.java]: Not possible, because the passed in pair are in different cases:

1. `initial.head` + `values`
2. `values.head` + `values.tail`
3. `reducedValue.head` + `tail.tail`

File: core/src/main/java/io/parsingdata/metal/token/Cho.java (hunk 1 above)
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/token/Cho.java]: Yes and no. There doesn't appear to be a use for an `Optional<Environment>` here at all, so I just changed it to `Environment`, which eliminates the `get()` outright.

But I did notice that there is no checking for `null` on both the `scope` and `environment` arguments (`encoding` is checked because it's explicitly allowed to be `null`). But before I make a big change like this while resolving some unrelated PR, let's investigate further: #175.

File: core/src/main/java/io/parsingdata/metal/token/TokenRef.java (hunk 2 above)
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/token/TokenRef.java]: The rule was the put the return of a value on the same line, but actual code on a new line. So I agree on the bottom one but the others are just values.

File: core/src/test/java/io/parsingdata/metal/TrampolineTest.java (hunk 3 above)
Comment (jvdb) [inline core/src/test/java/io/parsingdata/metal/TrampolineTest.java]: I think the non-trampolined version stack overflowed somewhere between 1k and 10k (with my default stack size).

File: core/src/main/java/io/parsingdata/metal/data/DataExpressionSource.java (hunk 6 above)
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/DataExpressionSource.java]: With regard to methods: that's a good style. With private methods I tend to just immediately call the lowest level version :-)

With regard to final question: I think that's checked in the line above it?

**Comment by jvdb** [comment]
@ccreeten: Excellent point. I haven't noticed significant slowdowns, but a somewhat comparative test is a good idea!

File: core/src/main/java/io/parsingdata/metal/data/ImmutableList.java (hunk 8 above)
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/data/ImmutableList.java]: Oh good point. The duplication can prevent the creation of an unnecessary trampoline :) In this case I will go for maintainability (= prevent duplication).

Comment (ccreeten) [inline core/src/main/java/io/parsingdata/metal/data/ImmutableList.java]: But what if the added check is more expensive? CPU don't like branching :laughing:

File: core/src/main/java/io/parsingdata/metal/data/DataExpressionSource.java (hunk 6 above)
Comment (ccreeten) [inline core/src/main/java/io/parsingdata/metal/data/DataExpressionSource.java]: Yes, it is a bit tied to the style mentioned above. The method itself does not check it's parameters. But again, although I'd personally do it, for private methods I think it can be left as is.

File: core/src/main/java/io/parsingdata/metal/expression/value/Fold.java (hunk 17 above)
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/expression/value/Fold.java]: Ah, missed that! Got it.

File: core/src/main/java/io/parsingdata/metal/token/TokenRef.java [hunk 18]
```diff
@@ -60,22 +64,22 @@ public TokenRef(final String name, final String referenceName, final Encoding en
...
+        return lookup(ImmutableList.create(environment.order), referenceName).computeResult().parse(scope, environment, encoding);
     }
 
-    private Token lookup(final ParseItem item, final String referenceName) {
-        if (item.getDefinition().name.equals(referenceName)) {
-            return item.getDefinition();
+    private SafeTrampoline<Token> lookup(final ImmutableList<ParseItem> items, final String referenceName) {
+        if (items.isEmpty()) { return complete(() -> LOOKUP_FAILED); }
+        final ParseItem item = items.head;
+        if (item.getDefinition().name.equals(referenceName)) { return complete(item::getDefinition); }
```
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/token/TokenRef.java]: One final thing: We need to do a bit of code style cleanup.

Why is this all one line:

```java
if (item.getDefinition().name.equals(referenceName)) { return complete(item::getDefinition); }
```

But this isn't? (From `While.java`, below.)

```java
        if (!environment.isPresent()) {
            return complete(Util::failure);
        }
```

As you might expect, the second style has my preference. Code style used to be a bit more consistent before this PR :relaxed:

File: core/src/main/java/io/parsingdata/metal/data/selection/ByName.java [hunk 19]
```diff
@@ -56,20 +60,26 @@ public static ParseValue getValue(final ParseGraph graph, final String name) {
...
-        }
-        return tailResults;
+    private static SafeTrampoline<ImmutableList<Value>> getAllValuesRecursive(final ImmutableList<ParseGraph> graphList, final ImmutableList<Value> valueList, final String name) {
+        if (graphList.isEmpty()) { return complete(() -> valueList); }
+        final ParseGraph graph = graphList.head;
+        if (graph.isEmpty()) { return intermediate(() -> getAllValuesRecursive(graphList.tail, valueList, name)); }
+        return intermediate(() -> getAllValuesRecursive(addIfGraph(graphList.tail.add(graph.tail), graph.head),
+                                                        addIfMatchingValue(valueList, graph.head, name),
+                                                        name));
+    }
```
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/data/selection/ByName.java]: that's my boy

File: core/src/main/java/io/parsingdata/metal/token/TokenRef.java (hunk 18 above)
Comment (rdvdijk) [inline core/src/main/java/io/parsingdata/metal/token/TokenRef.java]: And to add to that.

Previously 'simple' return statements have now become 'not so simple'. E.g.:

This was previously accepted by our own code style rules:

```java
if (something) { return head; }
```

In _many_ cases, this has now turned into:

```java
if (something) { return complete(() -> head); }
```

No so 'simple' anymore... Food for thought.

Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/token/TokenRef.java]: We will have to do another round of cleanup before release.

File: core/src/test/java/io/parsingdata/metal/TrampolineTest.java [hunk 20]
```diff
@@ -0,0 +1,78 @@
...
+        ((SafeTrampoline.CompletedTrampoline<Integer>) () -> 42).next();
+    }
+
+    @Test
+    public void noStackOverflow() {
+        // The 100000th Fibonacci number has 20899 digits
+        assertEquals(20899, fibonacci(BigInteger.ZERO, BigInteger.ONE, 100000).computeResult().toString().length());
+    }
+
+    private SafeTrampoline<BigInteger> fibonacci(final BigInteger l, final BigInteger r, final long count) {
```
Comment (mvanaken) [inline core/src/test/java/io/parsingdata/metal/TrampolineTest.java]: This is awesome! 😎

File: core/src/main/java/io/parsingdata/metal/SafeTrampoline.java [hunk 21]
```diff
@@ -0,0 +1,52 @@
...
+    @Override
+    default T computeResult() {
+        SafeTrampoline<T> current = this;
+        while (current.hasNext()) {
+            current = current.next();
+        }
+        return current.result();
+    }
+
+    static <T> SafeTrampoline<T> complete(final CompletedTrampoline<T> completedTrampoline) { return completedTrampoline; }
```
Comment (jvdb) [inline core/src/main/java/io/parsingdata/metal/SafeTrampoline.java]: Correct! Without these methods we could still directly use lambda's, but they would need to be type casted. So these methods prevent that by explicitly naming the types of the functional interfaces involved.

**Comment by ccreeten** [comment]
Funny, my Eclipse could not compile lambdas referring to the inheritance trampoline interfaces (it didn't see the safe completed trampoline as a functional interface). Only in the most recent version it appears to be solved.

On that note, perhaps you could annotate all functional interfaces with @FunctionalInterface, so it becomes clear which are the case, and added with that, static checking to verify it.
